Repository suomipelit/kops, pull requests merged in 2019-10, with the labels that each got.

#28 Key repeat blocking
  src/kops.c
  src/wport.c
  src/wport.h
Labels: area:io

#30 Warning fixes
  src/game.c
  src/init.c
  src/menu.c
  src/spr.c
  src/util/utilcore.c
  src/util/utilcore.h
  src/util/utilfile.c
  src/util/utilfile.h
  src/weapon.c
Labels: type:cleanup

#31 Variable speed
  README.md
  src/game.c
  src/menu.c
  src/timer.c
  src/timer.h
  src/wport.c
Labels: area:io, type:enhancement
